project_name: lw
version: 2

before:
  hooks:
    - mkdir -p completions
    - sh -c "go run ./cmd/lw/main.go @completion bash > completions/lw.bash"
    - sh -c "go run ./cmd/lw/main.go @completion zsh > completions/lw.zsh"
    - sh -c "go run ./cmd/lw/main.go @completion fish > completions/lw.fish"

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/lw/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X github.com/kernel/leaseweb-cli/pkg/cmd.Version={{.Version}}'

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: '{{ .ProjectName }}'
    main: ./cmd/lw/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X github.com/kernel/leaseweb-cli/pkg/cmd.Version={{.Version}}'

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/lw/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X github.com/kernel/leaseweb-cli/pkg/cmd.Version={{.Version}}'

archives:
  - id: linux-archive
    ids: [linux]
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [tar.gz]
    files:
      - completions/*
  - id: macos-archive
    ids: [macos]
    name_template: '{{ .ProjectName }}_{{ .Version }}_macos_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    files:
      - completions/*
  - id: windows-archive
    ids: [windows]
    name_template: '{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    files:
      - completions/*

snapshot:
  version_template: '{{ .Tag }}-next'

nfpms:
  - license: Apache-2.0
    maintainer: Kernel <support@kernel.sh>
    bindir: /usr
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

brews:
  - name: lw
    repository:
      owner: kernel
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/kernel/leaseweb-cli
    description: CLI for the Leaseweb API
    license: Apache-2.0
    directory: Formula
    install: |
      bin.install "lw"
      bash_completion.install "completions/lw.bash" => "lw"
      zsh_completion.install "completions/lw.zsh" => "_lw"
      fish_completion.install "completions/lw.fish"
    test: |
      system "#{bin}/lw", "--version"
